# This workflow will do a clean install of node dependencies, build the source code and run the E2E tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: E2E Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Install Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 14.x
    - run: pnpm install
    - run: cd integration/project
    - run: pnpm bazel build //:npm --config=release
    - run: xvfb-run -a pnpm run test:e2e
      if: runner.os == 'Linux'
    - run: pnpm run test:e2e
      if: runner.os != 'Linux'
